# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20190807_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.CharField(max_length=45),
        ),
    ]
