# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20190807_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateTimeField(max_length=45),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateTimeField(max_length=45),
        ),
    ]
