# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20190808_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('start', models.DateTimeField(max_length=45)),
                ('end', models.DateTimeField(max_length=45)),
                ('notes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='exam_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
