# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-08 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_auto_20190808_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Book',
        ),
    ]
