# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_auto_20190808_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone',
            field=models.IntegerField(default=10),
        ),
    ]
