# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_book_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
