# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_auto_20190814_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.IntegerField(max_length=25),
        ),
    ]
